TARGET_BINS=maildirmerge maildirsizes maildircheck maildirreconstruct maildirarchive maildirdate2filename

EXTRA_BINS=maildirduperem

server_types=servertypes server_courier

MODS_maildirmerge=maildirmerge $(server_types) filetools
MODS_maildirsizes=maildirsizes
MODS_maildircheck=maildircheck filetools
MODS_maildirreconstruct=maildirreconstruct filetools $(server_types)
MODS_maildirarchive=maildirarchive
MODS_maildirdate2filename=maildirdate2filename $(server_types) filetools

include Makefile.inc
